name: mars_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.8

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  file_picker: ^5.3.1
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_signature_pad: ^3.0.1
  http: ^0.13.6
  image_painter: ^0.6.0
  open_file: ^3.3.2
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/sample.jpg
