name: Firebase Build IOS

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: 

jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install certificates and provisioning profile
        env:
          P12_DISTRIBUTION_CERTIFICATE_BASE64: "${{ secrets.CERTIFICATE_P12 }}"
          PROVISIONING_PROFILE: "${{ secrets.PROVISIONING_PROFILE }}"
          # KEYCHAIN_PASSWORD: "${{ secrets.IOS_RUNNER_LOCAL_KEYCHAIN_PASSWORD }}"
          # EXPORT_OPTIONS_BASE64: "${{ secrets.IOS_EXPORT_OPTIONS_BASE64 }}"
          

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.11' # Specify the version of Flutter you are using

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        run: |
          cd ios
          pod install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

    # - name: Build iOS app
      #   run: flutter build ios --release

      - name: Build IPA
        run: flutter build ipa --release

      - name: Deploy to Firebase App Distribution
        run: firebase appdistribution:distribute build/ios/ipa/mars_test.ipa --app ${{ secrets.FIREBASE_APP_ID_IOS }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}