name: Firebase Build IOS

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: 

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install certificates and provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > certificate.p12
          echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > profile.mobileprovision
          security create-keychain -p actions ios-build.keychain
          security import certificate.p12 -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
          security list-keychains -s ios-build.keychain
          security default-keychain -s ios-build.keychain
          security unlock-keychain -p actions ios-build.keychain
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.11' # Specify the version of Flutter you are using

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        run: |
          cd ios
          pod install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

    # - name: Build iOS app
      #   run: flutter build ios --release

      - name: Build IPA
        run: flutter build ipa --release

      - name: Deploy to Firebase App Distribution
        run: firebase appdistribution:distribute build/ios/ipa/mars_test.ipa --app ${{ secrets.FIREBASE_APP_ID_IOS }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}