name: Firebase Build

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: 

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.11' # Specify the version of Flutter you are using

      - name: Install dependencies
        run: flutter pub get

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build APK
        run: flutter build ipa --release

      - name: Deploy to Firebase App Distribution
        run: firebase appdistribution:distribute build/ios/ipa/mars_test.ipa --app ${{ secrets.FIREBASE_APP_ID_IOS }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}