name: Firebase Build IOS

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: 

jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest

    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install certificates and provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > certificate.p12
          echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > profile.mobileprovision
          # Create a custom keychain
          security create-keychain -p actions build.keychain
          security default-keychain -s build.keychain
          security import certificate.p12 -k build.keychain -P "" -T /usr/bin/codesign
          # Unlock the keychain
          security unlock-keychain -p actions build.keychain
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain

          # Install the provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # Specify the version of Flutter you are using

      - name: Install dependencies
        run: flutter pub get

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build iOS app
        run: flutter build ios --release

      - name: Deploy to Firebase App Distribution
        run: firebase appdistribution:distribute build/ios/ipa/mars_test.ipa --app ${{ secrets.FIREBASE_APP_ID_IOS }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}